apiVersion: v1
kind: Service
metadata:
    name: avinashpullurusunbirdtelemetryservice
spec:
    type: LoadBalancer
    ports:
    - port: 9001 
    selector:
        app: avinashpullurusunbirdtelemetryservice